Support partial reading of string tables
gimli-rs/object pull request #326
Opened 2021-06-15 01:47 UTC by mstange

Before this PR, StringTables are read in their entirety and do not make use of the partial read ability of `ReadRef`. This is fine in most cases, but it is problematic for the dyld shared cache.
The dyld shared cache has a shared string table which is about 340MB big. Only a fraction of those strings are needed by each embedded library. For example, if I dump all AppKit symbols with their names from the dyld shared cache on macOS 11.3, this patch reduces the number of bytes read from 347.4 MB to 4.8 MB.

This patch makes use of the relatively new `read_bytes_at_until` method. But it also extends it by one parameter, `upper_bound`, so that the string table's size can be honored.

We currently have a hardcoded limit of 4096 bytes for the string length in the ReadCache. It's possible that this limit is not appropriate in all the cases where `read_bytes_at_until` is now called. But I'm not changing it in this patch.

2021-06-15 07:35 UTC, philipc requested changes
Thanks! Hopefully Wasm will get mmap support eventually.

2021-06-15 07:35 UTC, philipc commented on src/read/util.rs
> +            Some(data) => data.read_bytes_at_until(self.start + offset as u64, 0, self.end),
Use either `checked_add` (probably more appropriate) or `wrapping_add`.

2021-06-15 07:35 UTC, philipc commented on src/read/read_ref.rs
> +    fn read_bytes_at_until(self, offset: u64, delimiter: u8, upper_bound: u64) -> Result<&'a [u8]>;
Maybe a `Range<u64>` would be clearer, or at least place `upper_bound` after `offset`?

2021-06-15 07:35 UTC, philipc commented on src/read/read_cache.rs
> +                let max_check = (upper_bound - offset) as usize;
We could incorporate the `4096` limit here.

2021-06-15 07:35 UTC, philipc commented on src/read/pe/section.rs
> +    fn name(&self) -> Result<Option<&'file str>> {
Why does this need changing? The trait doesn't have this bound.

2021-06-15 07:35 UTC, philipc commented on src/read/macho/load_command.rs
> +            .checked_add(self.strsize.get(endian) as u64)
Please use `from` or `into` instead of `as` so that's it is clearly non-lossy.

2021-06-15 15:40 UTC, mstange commented on src/read/coff/section.rs
> +    pub fn name<'data, 'file, R: ReadRef<'data>>(
I found a better solution to this. I'm going to have a commit before the main patch that switches some of the `'file` lifetimes to `'data` lifetimes, and that will solve the lifetime trouble I ran into here.

2021-06-16 01:53 UTC, philipc approved these changes

2021-06-16 01:53 UTC, merged

2021-07-19 02:38 UTC, mstange commented
@philipc Could you make a release which contains this commit?

2021-07-19 03:16 UTC, philipc commented
Can it wait a week or so? I'm currently hoping to get an alternative to #325 implemented before doing a release.

2021-07-19 03:17 UTC, mstange commented
Sure, that's fine.