elf: add EF_MIPS_ABI_* e_flags constants
gimli-rs/object pull request #433
Opened 2022-05-01 05:34 UTC by ayrtonm

This adds a few constants that are needed to fix some targets that are broken on nightly rustc. Values were taken from the [LLVM source](https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/BinaryFormat/ELF.h#L518-L521).

2022-05-01 05:49 UTC, philipc requested changes
Please add `EF_MIPS_ABI` too. Also add support in the `readobj` example. There's existing support for `EF_MIPS_ARCH` that you can use as a guide.

2022-05-01 06:09 UTC, ayrtonm commented
I just added the `EF_MIPS_ABI` mask and updated `readobj`. I'm not entirely sure whether `EF_MIPS_ABI2` should be moved to the new flags section in `readobj` or not. I kept it where it was since the `EF_MIPS_ABI` mask doesn't cover `EF_MIPS_ABI2`, but I could see an argument for either case.

2022-05-01 06:11 UTC, philipc commented
I think `EF_MIPS_ABI2` is correct where it is, because, as you say, it is not covered by the `EF_MIPS_ABI` mask.

2022-05-01 06:35 UTC, ayrtonm commented
The existing MIPS test files show `<unknown> (0x0)` for the new field since they use the 64-bit ABI. I have a MIPS binary using the O32 ABI that I can check in to the `object-testfiles` repo to actually test the new flags. Is there anything else I'd need to do to update the tests?

2022-05-01 06:49 UTC, philipc commented
As long as the tests pass for you locally, then this PR would just need to update the submodule too. I don't think there's anything else.

2022-05-01 06:54 UTC, philipc commented
We may want to check that the `EF_MIPS_ABI` fields is non-zero, rather than printing unknown. For example: https://github.com/gimli-rs/object/blob/f18fc4bac74e1b744aca6543780edfdf26e945f2/crates/examples/src/readobj/pe.rs#L423-L429

2022-05-02 01:31 UTC, ayrtonm commented
> We may want to check that the EF_MIPS_ABI fields is non-zero, rather than printing unknown.

Done and I updated the testfile references. I think the only thing left is updating the submodule, but I assume that has to be after the [test binaries are merged](https://github.com/gimli-rs/object-testfiles/pull/3).

2022-05-02 05:58 UTC, philipc approved these changes

2022-05-02 06:39 UTC, merged

2022-05-02 06:39 UTC, philipc commented
Thanks! I'm guessing you want a release with this, so I'll try to do one in the near future.

2022-05-08 21:15 UTC, overdrivenpotato commented
A release would help fix some issues in the [`rust-psp`](https://github.com/overdrivenpotato/rust-psp) target too 🙂

2022-05-09 07:53 UTC, philipc commented
Published 0.28.4.