Support Aarch64Call relocations for Mach-O
gimli-rs/object pull request #465
Opened 2022-09-19 01:52 UTC by nathanwhit

This PR adds support for relocations with  `RelocationEncoding::Aarch64Call`  on Mach-O. Before this PR we would panic, as the relocation has a size of 26 which was unhandled, and we weren't setting the appropriate `r_type`. After this PR we support relocations with `RelocationEncoding::Aarch64Call` and an arbitrary addend.

This PR also handles a few extra cases of the relocation size (21 and 12) in order to support the usage of Mach-O specific relocations like `ARM64_RELOC_PAGE21` and `ARM64_RELOC_PAGEOFF12`, respectively.

2022-09-19 02:04 UTC, philipc commented
Thanks! Based on a brief look this is good. Where was the panic occurring?

2022-09-19 03:43 UTC, nathanwhit commented
The original panic was at https://github.com/gimli-rs/object/blob/13c139286e0923fa3d0120bd7e5319bc19236cf5/src/write/macho.rs#L551 Once that was fixed, it was hitting https://github.com/gimli-rs/object/blob/13c139286e0923fa3d0120bd7e5319bc19236cf5/src/write/macho.rs#L599

2022-09-19 03:58 UTC, philipc commented
Ah okay, so not panics, just returning errors (maybe your crate was unwrapping that error).

2022-09-19 04:06 UTC, nathanwhit commented
Ah sorry, of course, don't know how I managed to misread that. The panic I was seeing was from cranelift unwrapping that error.

2022-09-21 07:34 UTC, philipc requested changes

2022-09-21 07:34 UTC, philipc commented on src/write/mod.rs
> +            }
Details that are specific to file formats shouldn't need to be known here. This should be handed in the `macho` module instead by returning zero from `macho_fixup_relocation`.

2022-09-21 07:34 UTC, philipc commented on src/write/macho.rs
> +                                r_symbolnum = (value + 4) as u32;
Instead of adding 4 here, change `macho_fixup_relocation` so that this isn't needed.

2022-09-21 07:34 UTC, philipc commented on src/write/macho.rs
> +                        12 | 21 | 26 | 32 => 2,
Maybe instead of this, change `reloc.size` to 32 in `macho_fixup_relocation` while you're doing the other special handling.

2022-09-22 00:53 UTC, philipc approved these changes
Thanks! I'll merge this after the unrelated archive code has been fixed.

2022-09-30 22:21 UTC, nathanwhit commented
(Rebased so that CI passes now that the formatting issue has been fixed on master)

2022-10-04 02:48 UTC, merged