Initial Xtensa support
gimli-rs/object pull request #481
Opened 2022-11-03 23:10 UTC by MabezDev

This PR adds the bare minimum Xtensa support to allow our Xtensa-enabled Rust fork to compile on stable 1.65, as we were running into https://github.com/rust-lang/rust/issues/102290 in our testing.

2022-11-03 23:50 UTC, philipc commented
Please add this architecture to the [`elf_any` test](https://github.com/gimli-rs/object/blob/389c43a7567df94bbb31c697f79ed473523a7089/tests/round_trip/mod.rs#L231). #430 is a PR that did this for another architecture.

2022-11-08 17:22 UTC, MabezDev commented
Thanks for the link to #430, was most helpful! I've gone ahead and implemented the relevant relocations for Xtensa and added the Xtensa arch to the test case as you requested.

2022-11-08 23:19 UTC, philipc requested changes

2022-11-08 23:19 UTC, philipc commented on src/write/elf/object.rs
> +                            (RelocationKind::Absolute, _, 32) => elf::R_XTENSA_32,
I don't think you meant to change this.

2022-11-08 23:19 UTC, philipc commented on src/write/elf/object.rs
> +                            (RelocationKind::Absolute, _, 32) => elf::R_XTENSA,
Should this be `R_XTENSA_32`?

2022-11-09 01:26 UTC, philipc requested changes
Please run `cargo fmt`.

2022-11-09 12:05 UTC, philipc approved these changes
Thanks!

2022-11-09 12:06 UTC, merged

2022-11-10 11:37 UTC, MabezDev commented
Thanks, @philipc! Are there any plans to cut a new release anytime soon?

2022-11-10 11:59 UTC, philipc commented
I'd like to do a release soon. However, there's a bit of XCOFF work in progress currently that I'd like to see polished a bit more first. I may consider doing a release with the XCOFF feature disabled somehow.