added a function to the symbol trait called "native_symbol"
gimli-rs/object pull request #494
Opened 2022-12-29 08:01 UTC by invlpg

This allows you to get a copy of the underlying native symbol structure.

2022-12-29 08:04 UTC, invlpg commented
https://github.com/gimli-rs/object/issues/493

2022-12-29 20:50 UTC, invlpg commented
Ready to merge

2022-12-30 01:29 UTC, philipc requested changes

2022-12-30 01:29 UTC, philipc commented on src/read/coff/symbol.rs
> +    /// get the raw ImageSymbol struct.
```suggestion
    /// Get the raw `ImageSymbol` struct.
```

2022-12-30 01:29 UTC, philipc commented on src/read/coff/symbol.rs
> +        *self.symbol
```suggestion
    pub fn raw_symbol(&self) -> &'data pe::ImageSymbol {
        self.symbol
```

2022-12-30 01:29 UTC, philipc commented on tests/read/coff.rs
> +fn coff_symbol_raw_test() {
Thanks for the diligence with regard to testing. However, I prefer not to have tests for trivial getter functions, so let's leave this out.

2023-01-02 07:03 UTC, invlpg commented
Ill make these changes real quick

2023-01-03 03:50 UTC, invlpg reviewed
cool

2023-01-03 03:59 UTC, philipc commented on tests/read/coff.rs
> +}
You need to revert this change.

2023-01-03 07:48 UTC, invlpg commented
ok ran cargo fmt

2023-01-03 08:00 UTC, philipc approved these changes

2023-01-03 08:01 UTC, philipc commented
Coverage failure is probably https://github.com/actions-rs/tarpaulin/issues/21

2023-01-03 08:02 UTC, merged