write: fix reserving empty section error
gimli-rs/object pull request #514
Opened 2023-02-16 11:18 UTC by lzw3232

if we copy a elf with a empty section and the sh_addralign is not 0, it will return a unaligned offset.

2023-02-16 11:36 UTC, philipc commented
Thanks for the PR. However, it does not look correct. Can you give an in depth explanation so I can better understand the problem? Are you running the `elfcopy` example? How does the unaligned offset cause an error?

2023-02-16 11:55 UTC, lzw3232 commented
> Thanks for the PR. However, it does not look correct. Can you give an in depth explanation so I can better understand the problem? Are you running the `elfcopy` example? How does the unaligned offset cause an error?

for example, the reserved_len is 64. then the first section's len is 42, align_start is 16. the offset is 64. But next section's len is 0,  align_start is 16. the offset should be 112, but the offset is 106.
you can run elfcopy with this elf https://github.com/lzw3232/test.

2023-02-16 12:07 UTC, philipc commented
Ok, and does that offset of 106 causes problems? It does sound like something that needs fixing, but I want to understand the problem first.

2023-02-16 15:42 UTC, lzw3232 commented
> 



> Ok, and does that offset of 106 causes problems? It does sound like something that needs fixing, but I want to understand the problem first.

yes，the 106/16 is not a integer.

2023-02-16 15:44 UTC, lzw3232 commented
> > Ok, and does that offset of 106 causes problems? It does sound like something that needs fixing, but I want to understand the problem first.
> 
> yes，the 106/16 is not a integer.

so it is a unaligned offset.

2023-02-17 04:30 UTC, philipc commented
Yes I understand what an unaligned offset is. What were you doing that caused you to notice that this is a problem?

I see that running elfcopy on it gives an error:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `106`,
 right: `112`', crates/examples/src/bin/elfcopy.rs:506:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Is that all that you were trying to do, or are you trying to use this code in something else where the unaligned offset causes a problem?

2023-02-17 04:40 UTC, lzw3232 commented
> Yes I understand what an unaligned offset is. What were you doing that caused you to notice that this is a problem?
> 
> I see that running elfcopy on it gives an error:
> 
> ```
> thread 'main' panicked at 'assertion failed: `(left == right)`
>   left: `106`,
>  right: `112`', crates/examples/src/bin/elfcopy.rs:506:21
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> Is that all that you were trying to do, or are you trying to use this code in something else where the unaligned offset causes a problem?

I just want to copy a elf with a empty section. This function said that "Returns the aligned offset of the start of the range". But if len is 0, it doesn't call "util::align" just return "self.len". Then I think this is a problem.

2023-02-17 05:04 UTC, philipc requested changes

2023-02-17 05:04 UTC, philipc commented on src/write/elf/writer.rs
> +        if align_start > 1 {
Can you also add this check to `write_align` please.

2023-02-17 05:25 UTC, philipc approved these changes
Thanks!

2023-02-17 05:27 UTC, merged