add support for csky arch(elf)
gimli-rs/object pull request #561
Opened 2023-07-14 08:10 UTC by Dirreke

2023-07-14 10:42 UTC, bjorn3 commented
All matches seem to be sorted by variant name. Could you insert the Csky variant at the right place to keep it sorted?

2023-07-14 10:43 UTC, bjorn3 commented on src/common.rs
> +    CSKY,
```suggestion
    Csky,
```
Rustc warns about non-CamelCase names.

2023-07-17 03:16 UTC, philipc requested changes
Thanks for the PR. Please also add support in these two places:
https://github.com/gimli-rs/object/blob/b237c5c603bda4fc77eec4db951d833b79cb543d/src/read/elf/file.rs#L154
https://github.com/gimli-rs/object/blob/b237c5c603bda4fc77eec4db951d833b79cb543d/tests/round_trip/mod.rs#L231

2023-07-18 10:29 UTC, philipc approved these changes

2023-07-18 10:29 UTC, merged

2023-07-29 06:48 UTC, Dirreke commented
When will the next version be released

2023-07-29 09:31 UTC, philipc commented
I don't think there's been any breaking changes yet, so I can do a point release when needed.

2023-08-13 05:59 UTC, philipc commented
0.32.0 has been published.