Support the arm64e architecture for macOS/iOS
gimli-rs/object pull request #574
Opened 2023-08-30 14:37 UTC by arttet

#573

2023-08-30 14:59 UTC, bjorn3 commented on src/write/elf/object.rs
> +            Architecture::Aarch64_Arm64e => elf::EM_AARCH64,
According to https://github.com/ARM-software/abi-aa/blob/main/pauthabielf64/pauthabielf64.rst#appendix-alternative-elf-marking-using-gnu-program-properties `GNU_PROPERTY_AARCH64_FEATURE_PAUTH` in `.note.gnu.property` indicates that pointer authentication is used.

2023-08-31 01:33 UTC, philipc commented on crates/examples/src/readobj/elf.rs
> +                                    if let Some(val) = property.data_u32(endian).print_err(p) {
According to the ABI, this value "is at least two 64-bit words, the first being a platform identifier, and the second being a version number specific to the platform identified in the first word".

2023-08-31 01:45 UTC, philipc commented
For the purposes of this crate, is `Architecture::Aarch64_Arm64e` identical to `Architecture::Aarch64` except for the Mach-O CPU subtype? My instinct is that we should add a method to `write::Object` to set the Mach-O CPU subtype instead of adding a new `Architecture` variant for this.

2023-08-31 12:31 UTC, philipc requested changes

2023-08-31 12:31 UTC, philipc commented on src/write/macho.rs
> +    /// Specify information for a Mach-O CPU subtype.
```suggestion
    /// Specify the Mach-O CPU subtype.
```

2023-08-31 12:31 UTC, philipc commented on src/write/macho.rs
> +    pub fn set_cpu_subtype(&mut self, cpu_subtype: u32) {
```suggestion
    pub fn set_macho_cpu_subtype(&mut self, cpu_subtype: u32) {
```

2023-08-31 12:31 UTC, philipc commented on src/write/mod.rs
> +    cpu_subtype: Option<u32>,
```suggestion
    macho_cpu_subtype: Option<u32>,
```

2023-08-31 21:34 UTC, philipc approved these changes

2023-09-01 06:27 UTC, arttet commented
Can we merge it?

P.S. https://github.com/rust-lang/rust/issues/115218

2023-09-03 02:55 UTC, merged

2023-09-03 03:06 UTC, philipc commented
Published in 0.32.1