elf: parse library from symbol versioning table
gimli-rs/object pull request #693
Opened 2024-06-07 09:00 UTC by robbje

2024-06-07 09:30 UTC, philipc commented on crates/examples/testfiles/elf/base.objdump
> +Import { library: "GLIBC_2.2.5", name: "__cxa_finalize" }
The version info for this file looks like:
```
    VersionNeed {
        Version: 1
        AuxCount: 1
        Filename: "libc.so.6" (0x1)
        AuxOffset: 16
        NextOffset: 0
        Aux {
            Hash: 0x9691A75
            Flags: 0x0
            Index: 2
            Name: "GLIBC_2.2.5" (0x33)
            NextOffset: 0
        }
    }
```

I would have expected the `name` for these to be `libc.so.6`.

2024-06-07 12:32 UTC, philipc requested changes

2024-06-07 12:32 UTC, philipc commented on src/read/elf/file.rs
> +        let svt = self.sections.versions(self.endian, self.data)?;
We don't want to call this for every import. We've already called it in `imports`, so `svt` could be passed as a parameter to this function.

2024-06-07 12:32 UTC, philipc commented on src/read/elf/file.rs
> +                    while let Some((verneed, mut vernaux_iter)) = verneed_iter.next()? {
Parsing all these verneed entries again for every import isn't ideal. We already parsed them once when building `svt`. The problem is we didn't store the parsed info in `svt`. We can probably add another field in [`Version`](https://github.com/gimli-rs/object/blob/2f45bc0e1b82df1229453ceed1361b8558b8529b/src/read/elf/version.rs#L38).

2024-06-08 02:00 UTC, philipc requested changes
Thanks, this is getting close, just some style changes now.

2024-06-09 11:58 UTC, robbje commented
Thanks for the reviews.

2024-06-09 13:18 UTC, merged