Add 2 new  constants
gimli-rs/object pull request #720
Opened 2024-08-18 22:36 UTC by marxin

There constants were added recently in `2.43` (https://github.com/bminor/binutils-gdb/blob/f9b44496e631edfa5c8218699d5a5ffe59b21033/include/elf/common.h#L613C37-L614).

2024-08-19 05:06 UTC, philipc requested changes
Thanks.  Can you place them after `SHF_MASKOS`, and also add them to `crates/examples/src/readobj/elf.rs` (which I notice is missing `SHF_EXCLUDE`).

2024-08-19 05:50 UTC, philipc approved these changes

2024-08-19 05:51 UTC, merged

2024-08-19 05:53 UTC, marxin commented
Thanks for merging the change. I want to use the change in the `wild` linker.

Any estimation about a new release of `object` crate?

2024-08-19 06:07 UTC, philipc commented
No plan for a release, but can do one if needed.

Have you already checked for more missing constants in `wild`?

2024-08-27 08:58 UTC, marxin commented
Please make a release, now I can't see anything particular missing for `wild` ld.