Reformat code
gimli-rs/object pull request #725
Opened 2024-09-09 08:28 UTC by numas13

Reduce boilerplate code and reformat match for better readability.

2024-09-09 09:29 UTC, philipc requested changes

2024-09-09 09:29 UTC, philipc commented on src/write/elf/object.rs
> +        use Architecture as A;
I don't think this makes enough difference.

2024-09-09 09:29 UTC, philipc commented on src/write/elf/object.rs
> +        use RelocationKind as R;
```suggestion
        use RelocationKind as K;
```

2024-09-09 09:29 UTC, philipc commented on src/write/elf/object.rs
> +        let unsupported_reloc = || Err(Error(format!("unimplemented relocation {:?}", reloc)));
Good idea.

2024-09-09 09:29 UTC, philipc commented on src/write/elf/object.rs
> +        #[rustfmt::skip]
```suggestion
```
I don't think manual formatting is necessary here, and it makes it more difficult to change this code in future. I think avoiding line wrapping is enough.

2024-09-09 09:29 UTC, philipc commented on src/write/elf/object.rs
> +            A::Aarch64 => match (size, kind, encoding) {
Once these are changed back to using rustfmt, I think `size` last will still be better.

2024-09-09 09:45 UTC, numas13 commented
@philipc done.

2024-09-10 00:20 UTC, philipc approved these changes
Thanks!

2024-09-10 00:22 UTC, merged